import { useEffect, useMemo, useState } from 'react'
import { ApiError, api, money, uploadAsset } from './api'
import type { AnyRecord } from './types'
import WechatAdmins from './WechatAdmins'

const EMPTY_VEHICLE = { name: '', fullName: '', subtitle: '', description: '', specs: { maxLoadKg: 0, maxRangeKm: 0 }, applicableScenes: [], restrictions: [], supportedModes: ['single'], pricingDescription: { description: '最终价格由后台审核确认', startFrom: 0 }, tags: [], enabled: true, requiresApproval: false, sortOrder: 0 }

function OperationsSettingsContent() {
  const [tab, setTab] = useState<'vehicles' | 'banners' | 'pricing'>('vehicles')
  return <><div className="mode-tabs settings-tabs"><button className={tab === 'vehicles' ? 'active' : ''} onClick={() => setTab('vehicles')}>车型与图片</button><button className={tab === 'banners' ? 'active' : ''} onClick={() => setTab('banners')}>首页轮播</button><button className={tab === 'pricing' ? 'active' : ''} onClick={() => setTab('pricing')}>计费规则</button></div>{tab === 'vehicles' ? <Vehicles /> : tab === 'banners' ? <Banners /> : <Pricing />}</>
}

function Vehicles() {
  const [list, setList] = useState<AnyRecord[]>([]), [selected, setSelected] = useState<AnyRecord>(), [error, setError] = useState(''), [saving, setSaving] = useState(false)
  const load = async () => { try { const rows = await api<AnyRecord[]>('/operations/vehicles'); setList(rows); setSelected(current => current ? rows.find(row => row.id === current.id) ?? current : current) } catch (e) { setError((e as Error).message) } }
  useEffect(() => { void load() }, [])
  const save = async () => { if (!selected) return; setSaving(true); try { await api(`/operations/vehicles/${selected.id}`, { method: 'PUT', body: JSON.stringify(selected) }); await load() } catch (e) { setError((e as Error).message) } finally { setSaving(false) } }
  const upload = async (file?: File) => { if (!file || !selected) return; setSaving(true); try { const asset = await uploadAsset(file); await api(`/operations/vehicles/${selected.id}/images`, { method: 'POST', body: JSON.stringify({ ...asset, isPrimary: !selected.images?.length, sortOrder: selected.images?.length ?? 0 }) }); await load() } catch (e) { setError((e as Error).message) } finally { setSaving(false) } }
  return <section className="ops-grid"><div className="panel"><div className="panel-title"><h2>车型列表</h2><button onClick={() => setSelected({ ...EMPTY_VEHICLE, id: `vehicle-${Date.now()}` })}>新增车型</button></div><div className="ops-list">{list.map(row => <button key={row.id} className={selected?.id === row.id ? 'active' : ''} onClick={() => setSelected(row)}><b>{row.name}</b><span>{row.fullName}</span><small>{row.enabled ? '已上架' : '已下架'}</small></button>)}</div></div><div className="panel ops-editor">{selected ? <><div className="panel-title"><h2>编辑车型 · {selected.id}</h2><button className="primary" disabled={saving} onClick={save}>保存</button></div><div className="ops-form"><Field label="简称" value={selected.name} change={name => setSelected({ ...selected, name })} /><Field label="完整名称" value={selected.fullName} change={fullName => setSelected({ ...selected, fullName })} /><Field label="副标题" value={selected.subtitle} change={subtitle => setSelected({ ...selected, subtitle })} /><Field label="排序" type="number" value={selected.sortOrder} change={sortOrder => setSelected({ ...selected, sortOrder: +sortOrder })} /><label className="wide">描述<textarea value={selected.description ?? ''} onChange={e => setSelected({ ...selected, description: e.target.value })} /></label><Field label="载重 kg" type="number" value={selected.specs?.maxLoadKg} change={value => setSelected({ ...selected, specs: { ...selected.specs, maxLoadKg: +value } })} /><Field label="续航 km" type="number" value={selected.specs?.maxRangeKm} change={value => setSelected({ ...selected, specs: { ...selected.specs, maxRangeKm: +value } })} /><Field label="参考起步价（元）" type="number" value={selected.pricingDescription?.startFrom} change={value => setSelected({ ...selected, pricingDescription: { ...selected.pricingDescription, startFrom: +value } })} /><label>状态<select value={selected.enabled ? '1' : '0'} onChange={e => setSelected({ ...selected, enabled: e.target.value === '1' })}><option value="1">上架</option><option value="0">下架</option></select></label><label className="wide">车型图片（上传至 TOS）<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => void upload(e.target.files?.[0])} /><div className="thumbs">{selected.images?.map((url: string) => <img src={url} key={url} alt="车型" />)}</div></label></div>{error && <div className="alert error">{error}</div>}</> : <div className="empty"><b>请选择车型</b><span>可编辑资料、图片和上下架状态</span></div>}</div></section>
}

function Banners() {
  const [list, setList] = useState<AnyRecord[]>([]), [selected, setSelected] = useState<AnyRecord>(), [error, setError] = useState('')
  const load = async () => { try { setList(await api('/operations/banners')) } catch (e) { setError((e as Error).message) } }
  useEffect(() => { void load() }, [])
  const upload = async (file?: File) => { if (!file) return; try { const asset = await uploadAsset(file); setSelected(value => ({ ...value, imageUrl: asset.url, objectKey: asset.objectKey })) } catch (e) { setError((e as Error).message) } }
  const save = async () => { if (!selected) return; try { await api(`/operations/banners/${selected.id}`, { method: 'PUT', body: JSON.stringify(selected) }); await load() } catch (e) { setError((e as Error).message) } }
  return <section className="ops-grid"><div className="panel"><div className="panel-title"><h2>轮播列表</h2><button onClick={() => setSelected({ id: `banner-${Date.now()}`, title: '', imageUrl: '', linkType: 'vehicle', linkTarget: '', sortOrder: list.length, enabled: true })}>新增轮播</button></div><div className="ops-list">{list.map(row => <button key={row.id} onClick={() => setSelected(row)}><b>{row.title}</b><span>{row.linkType} · {row.linkTarget}</span><small>{row.enabled ? '展示中' : '已停用'}</small></button>)}</div></div><div className="panel ops-editor">{selected ? <><div className="panel-title"><h2>编辑轮播</h2><button className="primary" onClick={() => void save()}>保存</button></div><div className="ops-form"><label className="wide">图片<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => void upload(e.target.files?.[0])} />{selected.imageUrl && <img className="banner-preview" src={selected.imageUrl} alt="轮播预览" />}</label><Field label="标题" value={selected.title} change={title => setSelected({ ...selected, title })} /><label>跳转类型<select value={selected.linkType} onChange={e => setSelected({ ...selected, linkType: e.target.value })}><option value="vehicle">车型</option><option value="activity">活动</option><option value="monthly">包月</option><option value="service">服务</option></select></label><Field label="跳转目标" value={selected.linkTarget} change={linkTarget => setSelected({ ...selected, linkTarget })} /><Field label="排序" type="number" value={selected.sortOrder} change={sortOrder => setSelected({ ...selected, sortOrder: +sortOrder })} /><label>状态<select value={selected.enabled ? '1' : '0'} onChange={e => setSelected({ ...selected, enabled: e.target.value === '1' })}><option value="1">展示</option><option value="0">停用</option></select></label></div>{error && <div className="alert error">{error}</div>}</> : <div className="empty"><b>请选择轮播图</b></div>}</div></section>
}

function Pricing() {
  const [state, setState] = useState<AnyRecord>(), [config, setConfig] = useState<AnyRecord>(), [preview, setPreview] = useState<AnyRecord>(), [error, setError] = useState('')
  const fields = useMemo(() => [['baseDistanceMeters', '起步里程（米）'], ['baseFeeCents', '起步费（分）'], ['distanceFeePerKmCents', '超出里程单价（分/公里）'], ['coldChainFeeCents', '冷链附加费（分）'], ['overweightThresholdKg', '超重阈值（kg）'], ['overweightFeePerKgCents', '超重费（分/kg）'], ['nightFeeCents', '夜间费（分）'], ['remoteAreaFeeCents', '偏远地区费（分）'], ['defaultQuoteValidityHours', '报价有效小时']], [])
  const load = async () => { const value = await api<AnyRecord>('/operations/pricing'); setState(value); setConfig(value.draft?.config ?? value.published?.config ?? value.defaults) }
  useEffect(() => { void load().catch(e => setError(e.message)) }, [])
  const save = async () => { try { setState(await api('/operations/pricing/draft', { method: 'PUT', body: JSON.stringify({ config, expectedVersion: state?.draft?.version }) })) } catch (e) { setError((e as Error).message) } }
  const publish = async () => { try { if (!state?.draft) throw new Error('请先保存草稿'); const value = await api<AnyRecord>('/operations/pricing/publish', { method: 'POST', body: JSON.stringify({ expectedVersion: state.draft.version }) }); setState(value); setConfig(value.published.config) } catch (e) { setError(e instanceof ApiError && e.status === 409 ? '草稿已被其他管理员修改，请刷新' : (e as Error).message) } }
  const simulate = async () => { try { setPreview(await api('/operations/pricing/preview', { method: 'POST', body: JSON.stringify({ useDraft: true, input: { vehicleId: 'z5-2026', distanceMeters: 12000, weightKg: 450 } }) })) } catch (e) { setError((e as Error).message) } }
  if (!config) return <div className="full-state"><p>加载计费规则…</p></div>
  return <section className="panel ops-editor"><div className="panel-title"><div><h2>计费规则草稿</h2><small>已发布版本：{state?.published?.version ?? '无'} · 草稿版本：{state?.draft?.version ?? '未创建'}</small></div><div><button onClick={() => void simulate()}>预览建议价</button><button onClick={() => void save()}>保存草稿</button><button className="primary" onClick={() => void publish()}>发布</button></div></div><div className="ops-form pricing-form">{fields.map(([key, label]) => <Field key={key} label={label} type="number" value={config[key]} change={value => setConfig({ ...config, [key]: +value })} />)}</div>{preview && <div className="total"><span>示例订单建议价</span><strong>{money(preview.totalCents)}</strong><small>基础 {money(preview.baseFeeCents)} · 距离 {money(preview.distanceFeeCents)} · 车型 {money(preview.vehicleFeeCents)} · 服务 {money(preview.serviceFeeCents)}</small></div>}{error && <div className="alert error">{error}</div>}</section>
}

function Field({ label, value, change, type = 'text' }: { label: string; value: string | number | undefined; change: (value: string) => void; type?: string }) { return <label>{label}<input type={type} min={type === 'number' ? 0 : undefined} value={value ?? ''} onChange={e => change(e.target.value)} /></label> }

export default function OperationsSettings() { return <><OperationsSettingsContent /><WechatAdmins /></> }
