import { BadRequestException, ConflictException, Injectable, OnModuleInit, ServiceUnavailableException } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { TosClient } from '@volcengine/tos-sdk';
import { DatabaseService } from '../database/database.service';
import { CANONICAL_VEHICLES } from './vehicle-catalog.seed';

export const DEFAULT_PRICING={baseDistanceMeters:3000,baseFeeCents:2500,distanceFeePerKmCents:400,vehicleFeesCents:{'z2':0,'z5-2026':500,'l5':300,'l5-max':400,'z8':800,'z8-max':1000,'z5-c':1200,'z8-max-c':1800,'z5-multi':700},coldChainFeeCents:1500,overweightFeePerKgCents:50,overweightThresholdKg:300,nightFeeCents:1000,nightStartHour:22,nightEndHour:6,remoteAreaFeeCents:2000,remoteAreas:[],defaultQuoteValidityHours:24};
const json=(v:any)=>JSON.stringify(v),parse=(v:string)=>JSON.parse(v),utc=()=>new Date().toISOString();
@Injectable() export class OperationsService implements OnModuleInit{
 constructor(private db:DatabaseService){}
 async onModuleInit(){const t=utc(),insert=this.db.db.prepare('INSERT INTO vehicle_catalog VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');if(!(this.db.db.prepare('SELECT 1 FROM vehicle_catalog LIMIT 1').get())){for(const [sort,item] of CANONICAL_VEHICLES.entries()){const v:any=item;insert.run(v.id,v.name,v.fullName,v.subtitle,v.description,json(v.specs),json(v.applicableScenes),json(v.restrictions),json(v.supportedModes),json(v.pricingDescription),json(v.tags),v.enabled?1:0,v.requiresApproval?1:0,sort,t,t);}await this.seedVehicleImages();await this.seedBanners();}else{const update=this.db.db.prepare("UPDATE vehicle_catalog SET name=?,full_name=?,subtitle=?,description=?,specs_json=?,scenes_json=?,restrictions_json=?,modes_json=?,pricing_hint_json=?,tags_json=?,requires_approval=?,sort_order=?,updated_at=? WHERE id=? AND subtitle='' AND restrictions_json='[]' AND tags_json='[]'");for(const [sort,item] of CANONICAL_VEHICLES.entries()){const v:any=item;update.run(v.name,v.fullName,v.subtitle,v.description,json(v.specs),json(v.applicableScenes),json(v.restrictions),json(v.supportedModes),json(v.pricingDescription),json(v.tags),v.requiresApproval?1:0,sort,t,v.id);}if(!(this.db.db.prepare('SELECT 1 FROM vehicle_images LIMIT 1').get()))await this.seedVehicleImages();if(!(this.db.db.prepare('SELECT 1 FROM content_banners LIMIT 1').get()))await this.seedBanners();}}
 listVehicles(admin=false){const rows=this.db.db.prepare(`SELECT * FROM vehicle_catalog ${admin?'':'WHERE enabled=1'} ORDER BY sort_order,id`).all() as any[];return rows.map(v=>({id:v.id,name:v.name,fullName:v.full_name,subtitle:v.subtitle,description:v.description,enabled:!!v.enabled,requiresApproval:!!v.requires_approval,sortOrder:v.sort_order,specs:parse(v.specs_json),applicableScenes:parse(v.scenes_json),restrictions:parse(v.restrictions_json),supportedModes:parse(v.modes_json),pricingDescription:parse(v.pricing_hint_json),tags:parse(v.tags_json),images:(this.db.db.prepare('SELECT url FROM vehicle_images WHERE vehicle_id=? ORDER BY is_primary DESC,sort_order').all(v.id) as any[]).map(x=>x.url)}));}
 getVehicle(id:string){return this.listVehicles(true).find(v=>v.id===id);}
 saveVehicle(adminId:string,id:string,b:any){if(!id||!b.name||!b.fullName)throw new BadRequestException('车型名称不能为空');const t=utc(),exists=this.db.db.prepare('SELECT 1 FROM vehicle_catalog WHERE id=?').get(id);const values=[b.name,b.fullName,b.subtitle||'',b.description||'',json(b.specs||{}),json(b.applicableScenes||[]),json(b.restrictions||[]),json(b.supportedModes||['single']),json(b.pricingDescription||{}),json(b.tags||[]),b.enabled===false?0:1,b.requiresApproval?1:0,Number(b.sortOrder)||0,t,id];if(exists)this.db.db.prepare('UPDATE vehicle_catalog SET name=?,full_name=?,subtitle=?,description=?,specs_json=?,scenes_json=?,restrictions_json=?,modes_json=?,pricing_hint_json=?,tags_json=?,enabled=?,requires_approval=?,sort_order=?,updated_at=? WHERE id=?').run(...values);else this.db.db.prepare('INSERT INTO vehicle_catalog VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,...values.slice(0,13),t,t);this.audit(adminId,exists?'vehicle.update':'vehicle.create','vehicle',id,{name:b.name});return this.getVehicle(id);}
 listBanners(admin=false){return (this.db.db.prepare(`SELECT id,image_url imageUrl,title,link_type linkType,link_target linkTarget,sort_order sortOrder,enabled,created_at createdAt,updated_at updatedAt FROM content_banners ${admin?'':'WHERE enabled=1'} ORDER BY sort_order,id`).all() as any[]).map(v=>({...v,image:v.imageUrl,sort:v.sortOrder,enabled:!!v.enabled}));}
 saveBanner(adminId:string,id:string,b:any){if(!b.imageUrl||!b.title||!['vehicle','monthly','service','activity'].includes(b.linkType))throw new BadRequestException('轮播图信息不完整');if(b.linkType==='vehicle'&&!this.db.db.prepare('SELECT 1 FROM vehicle_catalog WHERE id=?').get(b.linkTarget))throw new BadRequestException('跳转车型不存在');const t=utc(),old=this.db.db.prepare('SELECT object_key FROM content_banners WHERE id=?').get(id) as any,key=b.objectKey||old?.object_key||'';this.db.db.prepare('INSERT INTO content_banners VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET image_url=excluded.image_url,object_key=excluded.object_key,title=excluded.title,link_type=excluded.link_type,link_target=excluded.link_target,sort_order=excluded.sort_order,enabled=excluded.enabled,updated_at=excluded.updated_at').run(id,b.imageUrl,key,b.title,b.linkType,b.linkTarget||'',Number(b.sortOrder)||0,b.enabled===false?0:1,t,t);this.audit(adminId,old?'banner.update':'banner.create','banner',id,{title:b.title});return this.listBanners(true).find((v:any)=>v.id===id);}
 pricing(){const draft=this.db.db.prepare("SELECT * FROM pricing_rule_versions WHERE status='draft' ORDER BY version DESC LIMIT 1").get() as any,published=this.db.db.prepare("SELECT * FROM pricing_rule_versions WHERE status='published' ORDER BY version DESC LIMIT 1").get() as any;return{draft:draft?{...draft,config:parse(draft.config_json)}:null,published:published?{...published,config:parse(published.config_json)}:null,defaults:DEFAULT_PRICING};}
 saveDraft(adminId:string,config:any,expectedVersion?:number){this.validatePricing(config);const current=this.db.db.prepare("SELECT * FROM pricing_rule_versions WHERE status='draft' ORDER BY version DESC LIMIT 1").get() as any,t=utc();if(current){if(expectedVersion!==undefined&&current.version!==expectedVersion)throw new ConflictException('计费草稿已被其他管理员修改');this.db.db.prepare('UPDATE pricing_rule_versions SET config_json=?,updated_at=? WHERE id=?').run(json(config),t,current.id);this.audit(adminId,'pricing.draft.update','pricing',current.id,{version:current.version});}else{const version=((this.db.db.prepare('SELECT max(version) v FROM pricing_rule_versions').get() as any).v||0)+1,id=randomUUID();this.db.db.prepare('INSERT INTO pricing_rule_versions VALUES(?,?,?,?,?,?,?,?,?)').run(id,version,'draft',json(config),adminId,null,t,t,null);this.audit(adminId,'pricing.draft.create','pricing',id,{version});}return this.pricing();}
 publish(adminId:string,expectedVersion:number){const draft=this.db.db.prepare("SELECT * FROM pricing_rule_versions WHERE status='draft' ORDER BY version DESC LIMIT 1").get() as any;if(!draft||draft.version!==expectedVersion)throw new ConflictException('计费草稿已变化，请刷新');const t=utc();this.db.db.transaction(()=>{this.db.db.prepare("UPDATE pricing_rule_versions SET status='archived' WHERE status='published'").run();this.db.db.prepare("UPDATE pricing_rule_versions SET status='published',published_by=?,published_at=?,updated_at=? WHERE id=? AND status='draft'").run(adminId,t,t,draft.id);})();this.audit(adminId,'pricing.publish','pricing',draft.id,{version:draft.version});return this.pricing();}
 preview(input:any,useDraft=false){const state=this.pricing(),config=(useDraft?state.draft?.config:state.published?.config)||state.defaults;return this.calculate(config,input);}
 calculate(c:any,input:any){const distance=Math.max(0,Number(input.distanceMeters)||0),weight=Math.max(0,Number(input.weightKg)||0),extraDistance=Math.max(0,distance-c.baseDistanceMeters),distanceFee=Math.round(extraDistance/1000*c.distanceFeePerKmCents),vehicleFee=Number(c.vehicleFeesCents?.[input.vehicleId]||0),cold=input.coldChain?c.coldChainFeeCents:0,over=Math.round(Math.max(0,weight-c.overweightThresholdKg)*c.overweightFeePerKgCents),night=input.night?c.nightFeeCents:0,remote=input.remote?c.remoteAreaFeeCents:0,total=c.baseFeeCents+distanceFee+vehicleFee+cold+over+night+remote;return{ruleVersion:(this.pricing().published as any)?.version||null,baseFeeCents:c.baseFeeCents,distanceFeeCents:distanceFee,vehicleFeeCents:vehicleFee,serviceFeeCents:cold+over+night+remote,discountCents:0,totalCents:total,distanceMeters:distance,breakdown:{coldChainFeeCents:cold,overweightFeeCents:over,nightFeeCents:night,remoteAreaFeeCents:remote},expiresAt:new Date(Date.now()+c.defaultQuoteValidityHours*3600000).toISOString()};}
 async upload(adminId:string,file:any,prefix:string){if(!file||!['image/jpeg','image/png','image/webp'].includes(file.mimetype)||file.size>5*1024*1024)throw new BadRequestException('仅支持 5MB 内 JPG、PNG、WebP 图片');const required=['TOS_ACCESS_KEY','TOS_SECRET_KEY','TOS_REGION','TOS_ENDPOINT','TOS_BUCKET','TOS_PUBLIC_BASE_URL'];if(required.some(k=>!process.env[k]))throw new ServiceUnavailableException('TOS 上传配置不完整');const ext=file.mimetype==='image/png'?'png':file.mimetype==='image/webp'?'webp':'jpg',key=`admin/${prefix}/${randomUUID()}.${ext}`,client=new TosClient({accessKeyId:process.env.TOS_ACCESS_KEY!,accessKeySecret:process.env.TOS_SECRET_KEY!,region:process.env.TOS_REGION!,endpoint:process.env.TOS_ENDPOINT!});await client.putObject({bucket:process.env.TOS_BUCKET!,key,body:file.buffer,contentType:file.mimetype});const url=`${process.env.TOS_PUBLIC_BASE_URL!.replace(/\/$/,'')}/${key}`;this.audit(adminId,'asset.upload','asset',key,{mime:file.mimetype,size:file.size});return{url,objectKey:key};}
 addVehicleImage(adminId:string,vehicleId:string,asset:any){if(!this.getVehicle(vehicleId))throw new BadRequestException('车型不存在');const id=randomUUID(),t=utc();this.db.db.transaction(()=>{if(asset.isPrimary)this.db.db.prepare('UPDATE vehicle_images SET is_primary=0 WHERE vehicle_id=?').run(vehicleId);this.db.db.prepare('INSERT INTO vehicle_images VALUES(?,?,?,?,?,?,?)').run(id,vehicleId,asset.url,asset.objectKey,asset.isPrimary?1:0,Number(asset.sortOrder)||0,t);})();this.audit(adminId,'vehicle.image.add','vehicle',vehicleId,{imageId:id});return this.getVehicle(vehicleId);}
 private vehicleSvg(name:string,color:string,icon:string){const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="400" height="260" viewBox="0 0 400 260"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="${color}"/><stop offset="100%" stop-color="${color}dd"/></linearGradient></defs><rect width="400" height="260" rx="16" fill="url(#bg)"/><text x="200" y="100" text-anchor="middle" font-size="48" font-weight="bold" fill="white" font-family="system-ui,sans-serif">${icon}</text><text x="200" y="160" text-anchor="middle" font-size="22" font-weight="600" fill="whitecc" font-family="system-ui,sans-serif">${name}</text><text x="200" y="195" text-anchor="middle" font-size="14" fill="white99" font-family="system-ui,sans-serif">九识智能 · 无人配送</text></svg>`;return'data:image/svg+xml;base64,'+Buffer.from(svg).toString('base64');}
 private bannerSvg(title:string,subtitle:string,color1:string,color2:string){const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="750" height="300" viewBox="0 0 750 300"><defs><linearGradient id="b" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="${color1}"/><stop offset="100%" stop-color="${color2}"/></linearGradient></defs><rect width="750" height="300" rx="20" fill="url(#b)"/><text x="375" y="130" text-anchor="middle" font-size="36" font-weight="bold" fill="white" font-family="system-ui,sans-serif">${title}</text><text x="375" y="185" text-anchor="middle" font-size="18" fill="whitecc" font-family="system-ui,sans-serif">${subtitle}</text></svg>`;return'data:image/svg+xml;base64,'+Buffer.from(svg).toString('base64');}
 private async seedVehicleImages(){const t=utc(),imgInsert=this.db.db.prepare('INSERT INTO vehicle_images VALUES(?,?,?,?,?,?,?)');const configs:[string,string,string][]=[['z2','#3B82F6','🚗'],['z5-2026','#10B981','🚐'],['l5','#8B5CF6','🚚'],['l5-max','#7C3AED','🚛'],['z8','#F59E0B','🚛'],['z8-max','#D97706','🚛'],['z5-c','#06B6D4','❄️'],['z8-max-c','#0891B2','❄️'],['z5-multi','#EC4899','📦'],['z8-chassis','#64748B','🔧'],['z5-security','#EF4444','🛡️'],['yokee','#F97316','🚌'],['l4-kit','#6366F1','⚙️']];for(const[vehicleId,color,icon]of configs){const vehicle=this.db.db.prepare('SELECT 1 FROM vehicle_catalog WHERE id=?').get(vehicleId);if(!vehicle)continue;const url=this.vehicleSvg(CANONICAL_VEHICLES.find(v=>v.id===vehicleId)?.name||vehicleId,color,icon);imgInsert.run(randomUUID(),vehicleId,url,'',1,0,t);}}
 private async seedBanners(){const t=utc(),bannerInsert=this.db.db.prepare('INSERT INTO content_banners VALUES(?,?,?,?,?,?,?,?,?,?)');const banners:[string,string,string,string,string][]=[['b1','按趟配送，即刻出发','灵活调度，城市末端高效送达','#3B82F6','#1D4ED8'],['b2','企业包月，省心省钱','固定线路包月方案，专属运力保障','#10B981','#059669'],['b3','冷链配送，品质保障','全程温控，生鲜医药安全送达','#06B6D4','#0891B2']];for(let i=0;i<banners.length;i++){const[id,title,sub,c1,c2]=banners[i];bannerInsert.run(id,this.bannerSvg(title,sub,c1,c2),'',title,i===0?'vehicle':'monthly',i===0?'z2':'',i,1,t,t);}}
 private validatePricing(c:any){const fields=['baseDistanceMeters','baseFeeCents','distanceFeePerKmCents','coldChainFeeCents','overweightFeePerKgCents','overweightThresholdKg','nightFeeCents','remoteAreaFeeCents','defaultQuoteValidityHours'];if(fields.some(k=>!Number.isFinite(Number(c[k]))||Number(c[k])<0))throw new BadRequestException('计费规则必须为非负数');if(c.nightStartHour<0||c.nightStartHour>23||c.nightEndHour<0||c.nightEndHour>23)throw new BadRequestException('夜间时段无效');}
 private audit(adminId:string,action:string,type:string,id:string,detail:any){this.db.db.prepare('INSERT INTO audit_logs VALUES(?,?,?,?,?,?,?)').run(randomUUID(),adminId,action,type,id,json(detail),utc());}}
