import { Text, View } from '@tarojs/components'
import Taro, { useLoad } from '@tarojs/taro'
import { useMemo, useState } from 'react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { adminRequest, getAdminInfo } from '@/services/admin-api'

type RecordValue = Record<string, any>
export default function AdminOrderDetail() {
  const [order, setOrder] = useState<RecordValue>(), [mode, setMode] = useState<'approve' | 'reject'>('approve'), [loading, setLoading] = useState(false), [error, setError] = useState('')
  const [form, setForm] = useState({ base: '0', distance: '0', vehicle: '0', service: '0', discount: '0', distanceMeters: '0', expiresAt: '', userNote: '', internalNote: '', rejectionReason: '' })
  const id = String(Taro.getCurrentInstance().router?.params.id || '')
  const load = () => adminRequest<RecordValue>({ url: `/api/admin/orders/${id}` }).then(setOrder).catch(reason => setError((reason as Error).message))
  useLoad(() => { void load() })
  const cents = (value: string) => Math.round(Number(value) * 100), total = useMemo(() => cents(form.base) + cents(form.distance) + cents(form.vehicle) + cents(form.service) - cents(form.discount), [form])
  const set = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }))
  const submit = async () => {
    if (mode === 'reject' && !form.rejectionReason.trim()) return setError('拒绝原因不能为空')
    if (mode === 'approve' && (!form.expiresAt || total < 0 || Object.values(form).slice(0, 5).some(value => Number(value) < 0))) return setError('请填写有效报价，优惠不能超过费用合计')
    setLoading(true); setError('')
    try { await adminRequest({ url: `/api/admin/orders/${id}/review`, method: 'POST', data: mode === 'approve' ? { decision: 'approve', baseFeeCents: cents(form.base), distanceFeeCents: cents(form.distance), vehicleFeeCents: cents(form.vehicle), serviceFeeCents: cents(form.service), discountCents: cents(form.discount), distanceMeters: Number(form.distanceMeters), expiresAt: new Date(form.expiresAt).toISOString(), userNote: form.userNote, internalNote: form.internalNote } : { decision: 'reject', rejectionReason: form.rejectionReason, internalNote: form.internalNote } }); await Taro.showToast({ title: '审核完成', icon: 'success' }); await load() } catch (reason) { const value = reason as Error & { statusCode?: number }; setError(value.statusCode === 409 ? '该订单已由其他管理员处理，请刷新查看' : value.message) } finally { setLoading(false) }
  }
  if (!order) return <View className="p-4"><Text className="block text-red-600">{error || '正在加载订单…'}</Text></View>
  const sender = order.addresses?.find((value: RecordValue) => value.role === 'sender'), receiver = order.addresses?.find((value: RecordValue) => value.role === 'receiver'), canReview = ['super_admin', 'operator'].includes(getAdminInfo()?.role || '') && order.status === 'pending_review'
  return <View className="min-h-screen bg-slate-50 p-4 space-y-3"><Card><CardContent className="p-4 space-y-2"><Text className="block text-lg font-semibold">{order.order_no}</Text><Text className="block text-sm">状态：{order.status}</Text><Text className="block text-sm">车型：{order.vehicle_id}</Text><Text className="block text-sm">预约：{order.scheduled_at ? new Date(order.scheduled_at).toLocaleString() : '立即用车'}</Text></CardContent></Card><Address title="寄件人" value={sender} /><Address title="收件人" value={receiver} /><Card><CardContent className="p-4 space-y-2"><Text className="block font-semibold">物品</Text>{order.items?.map((item: RecordValue) => <Text key={item.id} className="block text-sm">{item.name} × {item.quantity}，{item.estimated_weight_kg}kg</Text>)}</CardContent></Card>{canReview && <Card><CardContent className="p-4 space-y-3"><View className="flex gap-2"><Button className="flex-1" variant={mode === 'approve' ? 'default' : 'outline'} onClick={() => setMode('approve')}><Text>批准定价</Text></Button><Button className="flex-1" variant={mode === 'reject' ? 'destructive' : 'outline'} onClick={() => setMode('reject')}><Text>拒绝</Text></Button></View>{mode === 'approve' ? <><Money label="起步费（元）" value={form.base} change={value => set('base', value)} /><Money label="距离费（元）" value={form.distance} change={value => set('distance', value)} /><Money label="车型费（元）" value={form.vehicle} change={value => set('vehicle', value)} /><Money label="服务费（元）" value={form.service} change={value => set('service', value)} /><Money label="优惠（元）" value={form.discount} change={value => set('discount', value)} /><Money label="距离（米）" value={form.distanceMeters} change={value => set('distanceMeters', value)} /><Input value={form.expiresAt} onInput={event => set('expiresAt', event.detail.value)} placeholder="有效期，例如 2026-07-19T18:00" /><Textarea value={form.userNote} onInput={event => set('userNote', event.detail.value)} placeholder="给用户的说明" /><Text className="block text-xl font-bold text-blue-600">总价 ¥{(total / 100).toFixed(2)}</Text></> : <Textarea value={form.rejectionReason} onInput={event => set('rejectionReason', event.detail.value)} placeholder="拒绝原因（必填）" />}<Textarea value={form.internalNote} onInput={event => set('internalNote', event.detail.value)} placeholder="内部备注（用户不可见）" />{error && <Text className="block text-red-600">{error}</Text>}<Button className="w-full" disabled={loading} variant={mode === 'reject' ? 'destructive' : 'default'} onClick={submit}><Text>{loading ? '提交中…' : '确认提交审核'}</Text></Button></CardContent></Card>}</View>
}
function Address({ title, value }: { title: string; value?: RecordValue }) { return <Card><CardContent className="p-4 space-y-1"><Text className="block font-semibold">{title}：{value?.contact_name} {value?.phone}</Text><Text className="block text-sm">{[value?.province, value?.city, value?.district, value?.poi_name].filter(Boolean).join(' ')}</Text><Text className="block text-sm text-slate-500">{value?.formatted_address} {value?.detail_address}</Text></CardContent></Card> }
function Money({ label, value, change }: { label: string; value: string; change: (value: string) => void }) { return <View><Text className="block mb-1 text-sm">{label}</Text><Input type="digit" value={value} onInput={event => change(event.detail.value)} /></View> }
