import { CanActivate, ExecutionContext, Injectable, UnauthorizedException } from '@nestjs/common';
import { createHash, randomBytes, randomUUID, scryptSync, timingSafeEqual } from 'node:crypto';
import { DatabaseService } from '../database/database.service'; import { SqliteRepositories, hashToken } from '../database/sqlite.repositories';
export const hashPassword=(password:string)=>{const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(password,salt,64).toString('hex')}`};
export const verifyPassword=(password:string,stored:string)=>{const [salt,key]=String(stored||'').split(':');if(!salt||!key)return false;const expected=Buffer.from(key,'hex');if(expected.length!==64)return false;return timingSafeEqual(expected,scryptSync(password,salt,64));};
export const bearer=(h?:string)=>h?.startsWith('Bearer ')?h.slice(7):'';
@Injectable() export class UserAuthGuard implements CanActivate {constructor(private repos:SqliteRepositories,private db:DatabaseService){} canActivate(c:ExecutionContext){const req=c.switchToHttp().getRequest();let token=bearer(req.headers.authorization);if(!token&&process.env.NODE_ENV!=='production'&&process.env.ENABLE_DEV_AUTH==='true'){const openid=String(req.headers['x-dev-user']||'dev-user');const now=new Date().toISOString();let u=this.db.db.prepare('SELECT id FROM users WHERE openid=?').get(openid) as {id:string}|undefined;if(!u){u={id:randomUUID()};this.db.db.prepare('INSERT INTO users(id,openid,nickname,status,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(u.id,openid,openid,'active',now,now);}req.user={id:u.id};return true;}const s=this.repos.session.resolve(token);if(!s)throw new UnauthorizedException('用户未登录');req.user={id:s.userId};return true;}}
@Injectable() export class AdminAuthGuard implements CanActivate {constructor(private db:DatabaseService){} canActivate(c:ExecutionContext){const req=c.switchToHttp().getRequest();const cookie=String(req.headers.cookie||'').split(';').map((v:string)=>v.trim()).find((v:string)=>v.startsWith('admin_session='));const token=cookie?decodeURIComponent(cookie.slice(14)):bearer(req.headers.authorization);const row=this.db.db.prepare("SELECT a.id,a.username,a.role,s.expires_at expiresAt FROM admin_sessions s JOIN admin_users a ON a.id=s.admin_user_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>? AND a.status='active'").get(hashToken(token),new Date().toISOString());if(!row)throw new UnauthorizedException('管理员未登录或会话已过期');req.admin=row;return true;}}
export function issueSession(db:DatabaseService,userId:string,hours=24){const token=randomBytes(32).toString('base64url'),now=new Date(),expires=new Date(now.getTime()+hours*3600000);db.db.prepare('INSERT INTO user_sessions VALUES(?,?,?,?,?,?)').run(randomUUID(),userId,createHash('sha256').update(token).digest('hex'),expires.toISOString(),null,now.toISOString());return {token,expiresAt:expires.toISOString()};}
export function issueAdminSession(db:DatabaseService,adminId:string,hours=12){const token=randomBytes(32).toString('base64url'),now=new Date(),expires=new Date(now.getTime()+hours*3600000);db.db.prepare('INSERT INTO admin_sessions VALUES(?,?,?,?,?,?)').run(randomUUID(),adminId,hashToken(token),expires.toISOString(),null,now.toISOString());return {token,expiresAt:expires.toISOString()};}
