import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '../database/database.service';
const STATUSES=new Set(['pending_review','rejected','pending_payment','quote_expired','paid','dispatching','delivering','completed','cancelled','refund_pending','refunded']);
const mask=(v:string)=>v?.replace(/^(\d{3})\d{4}(\d{4})$/,'$1****$2')||'';
@Injectable() export class AdminOrdersService{constructor(private database:DatabaseService){}
 dashboard(){const start=new Date();start.setUTCHours(0,0,0,0);const count=(w:string,a:any[]=[])=>(this.database.db.prepare(`SELECT count(*) n FROM orders WHERE ${w}`).get(...a) as any).n;return{pendingReview:count("status='pending_review'"),pendingPayment:count("status='pending_payment'"),todayNew:count('created_at>=?',[start.toISOString()]),rejected:count("status='rejected'"),recentPending:this.list({status:'pending_review',page:1,pageSize:5}).items};}
 list(q:any){const page=Math.max(1,+q.page||1),pageSize=Math.min(100,Math.max(1,+q.pageSize||20)),w:string[]=[],a:any[]=[];if(q.status){if(!STATUSES.has(q.status))throw new BadRequestException('状态无效');w.push('o.status=?');a.push(q.status);}if(q.orderNo){w.push('o.order_no LIKE ?');a.push(`%${String(q.orderNo).slice(0,50)}%`);}if(q.keyword){w.push('(s.contact_name LIKE ? OR s.phone LIKE ?)');const k=`%${String(q.keyword).slice(0,50)}%`;a.push(k,k);}if(q.dateFrom){w.push('o.created_at>=?');a.push(new Date(q.dateFrom).toISOString());}if(q.dateTo){const d=new Date(q.dateTo);d.setUTCHours(23,59,59,999);w.push('o.created_at<=?');a.push(d.toISOString());}const c=w.length?`WHERE ${w.join(' AND ')}`:'',base=`FROM orders o LEFT JOIN order_addresses s ON s.order_id=o.id AND s.role='sender' LEFT JOIN order_addresses r ON r.order_id=o.id AND r.role='receiver' LEFT JOIN admin_users au ON au.id=o.reviewed_by ${c}`;const total=(this.database.db.prepare(`SELECT count(DISTINCT o.id) n ${base}`).get(...a) as any).n;const items=(this.database.db.prepare(`SELECT o.id,o.order_no orderNo,o.created_at createdAt,o.vehicle_id vehicleId,o.scheduled_at scheduledAt,o.status,s.contact_name contactName,s.phone,s.district senderDistrict,r.district receiverDistrict,au.username reviewer ${base} ORDER BY CASE WHEN o.status='pending_review' THEN 0 ELSE 1 END,o.created_at DESC LIMIT ? OFFSET ?`).all(...a,pageSize,(page-1)*pageSize) as any[]).map(v=>({...v,phone:mask(v.phone)}));return{items,total,page,pageSize,totalPages:Math.ceil(total/pageSize)};}
 detail(id:string,role:string){const o=this.database.db.prepare('SELECT o.*,u.nickname,au.username reviewer FROM orders o JOIN users u ON u.id=o.user_id LEFT JOIN admin_users au ON au.id=o.reviewed_by WHERE o.id=?').get(id) as any;if(!o)throw new NotFoundException('订单不存在');const pii=role==='super_admin'||role==='operator';const addresses=(this.database.db.prepare('SELECT * FROM order_addresses WHERE order_id=? ORDER BY role').all(id) as any[]).map(v=>pii?v:{...v,phone:mask(v.phone),detail_address:'***',longitude:null,latitude:null});const items=this.database.db.prepare('SELECT * FROM order_items WHERE order_id=?').all(id),quotes=this.database.db.prepare('SELECT q.*,a.username created_by_name FROM order_quotes q LEFT JOIN admin_users a ON a.id=q.created_by WHERE q.order_id=? ORDER BY q.created_at DESC').all(id),statusLogs=this.database.db.prepare("SELECT l.*,CASE WHEN l.operator_type='admin' THEN a.username ELSE l.operator_type END operator_name FROM order_status_logs l LEFT JOIN admin_users a ON a.id=l.operator_id WHERE l.order_id=? ORDER BY l.created_at").all(id),auditLogs=this.database.db.prepare("SELECT l.id,l.action,l.created_at,a.username admin_username FROM audit_logs l JOIN admin_users a ON a.id=l.admin_user_id WHERE l.resource_type='order' AND l.resource_id=? ORDER BY l.created_at DESC").all(id);return{...o,addresses,items,quotes,statusLogs,auditLogs};}
 reviews(q:any){const page=Math.max(1,+q.page||1),pageSize=Math.min(100,Math.max(1,+q.pageSize||20)),extra=q.result==='approved'?"AND l.action='order.approve'":q.result==='rejected'?"AND l.action='order.reject'":'';const total=(this.database.db.prepare(`SELECT count(*) n FROM audit_logs l WHERE l.resource_type='order' ${extra}`).get() as any).n,items=this.database.db.prepare(`SELECT l.id,l.action,l.created_at,o.id orderId,o.order_no orderNo,o.rejection_reason rejectionReason,a.username reviewer,(SELECT total_cents FROM order_quotes q WHERE q.order_id=o.id ORDER BY created_at DESC LIMIT 1) totalCents FROM audit_logs l JOIN orders o ON o.id=l.resource_id JOIN admin_users a ON a.id=l.admin_user_id WHERE l.resource_type='order' ${extra} ORDER BY l.created_at DESC LIMIT ? OFFSET ?`).all(pageSize,(page-1)*pageSize);return{items,total,page,pageSize,totalPages:Math.ceil(total/pageSize)};}}
